### ISSUE TITLE
Can't convert object to arrow

### ISSUE THREAD

**Issue by brandonhilkert** [ankane/polars-ruby#3]
I'll preface this with....I'm sure I'm doing something wrong.

Attempting to write out complex ruby objects gotten from AR to parquet files for Athena analysis. It seems to be choking on a certain type of object.

```ruby
    orders = []

    Order
      .includes(
        items:     [:item_return, :orderable],
        shipments: :items,
        invoices:  [],
      )
      .find_each do |order|
        orders << order.as_json(
          include: {
            items:     { include: [:item_return, :orderable] },
            shipments: { include: :items },
            invoices:  {},
          }
        ).merge("date" => Date.today.to_formatted_s)
      end

    df   = Polars::DataFrame.new({ orders: orders })
    file = Tempfile.new("orders")

    df.write_parquet(file.path, compression: "snappy")
```

```
>>     df.write_parquet(file.path, compression: "snappy")
thread '<unnamed>' panicked at 'cannot convert object to arrow', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/datatypes/dtype.rs:230:26
stack backtrace:
   0:     0x7f8e826ee960 - <unknown>
   1:     0x7f8e82715dbe - <unknown>
   2:     0x7f8e826eb805 - <unknown>
   3:     0x7f8e826ee725 - <unknown>
   4:     0x7f8e826eff7f - <unknown>
   5:     0x7f8e826efcba - <unknown>
   6:     0x7f8e826f0678 - <unknown>
   7:     0x7f8e826f03d1 - <unknown>
   8:     0x7f8e826eee0c - <unknown>
   9:     0x7f8e826f0132 - <unknown>
  10:     0x7f8e8035b003 - <unknown>
  11:     0x7f8e816fd673 - <unknown>
  12:     0x7f8e81dea52a - <unknown>
  13:     0x7f8e81707874 - <unknown>
  14:     0x7f8e80853f31 - <unknown>
  15:     0x7f8e806602e8 - <unknown>
  16:     0x7f8e807a8021 - <unknown>
  17:     0x7f8e807e9659 - <unknown>
  18:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  19:     0x7f8ea1d02e31 - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  20:     0x7f8ea1d02e31 - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:778
  21:     0x7f8ea1d08fbe - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2211
  22:     0x7f8ea1d13ac2 - eval_string_with_scope
                               at /tmp/ruby-3.1.1/vm_eval.c:1780
  23:     0x7f8ea1d13ac2 - rb_f_eval
                               at /tmp/ruby-3.1.1/vm_eval.c:1823
  24:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  25:     0x7f8ea1d02e31 - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  26:     0x7f8ea1d02e31 - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:778
  27:     0x7f8ea1d0960a - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2220
  28:     0x7f8ea1d141ce - invoke_block
                               at /tmp/ruby-3.1.1/vm.c:1316
  29:     0x7f8ea1d141ce - invoke_iseq_block_from_c
                               at /tmp/ruby-3.1.1/vm.c:1372
  30:     0x7f8ea1d141ce - invoke_block_from_c_bh
                               at /tmp/ruby-3.1.1/vm.c:1390
  31:     0x7f8ea1d141ce - vm_yield_with_cref
                               at /tmp/ruby-3.1.1/vm.c:1427
  32:     0x7f8ea1d141ce - vm_yield
                               at /tmp/ruby-3.1.1/vm.c:1435
  33:     0x7f8ea1d141ce - rb_yield_0
                               at /tmp/ruby-3.1.1/vm_eval.c:1347
  34:     0x7f8ea1d141ce - loop_i
                               at /tmp/ruby-3.1.1/vm_eval.c:1446
  35:     0x7f8ea1b1d343 - rb_vrescue2
                               at /tmp/ruby-3.1.1/eval.c:903
  36:     0x7f8ea1b1d58a - rb_rescue2
                               at /tmp/ruby-3.1.1/eval.c:884
  37:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  38:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  39:     0x7f8ea1d1266b - vm_call_method
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3750
  40:     0x7f8ea1d02f2d - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  41:     0x7f8ea1d02f2d - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:759
  42:     0x7f8ea1d08fbe - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2211
  43:     0x7f8ea1d0ad23 - invoke_iseq_block_from_c
                               at /tmp/ruby-3.1.1/vm.c:1372
  44:     0x7f8ea1d0ad23 - invoke_block_from_c_bh
                               at /tmp/ruby-3.1.1/vm.c:1390
  45:     0x7f8ea1d0ae45 - vm_yield_with_cref
                               at /tmp/ruby-3.1.1/vm.c:1427
  46:     0x7f8ea1d0ae45 - vm_yield
                               at /tmp/ruby-3.1.1/vm.c:1435
  47:     0x7f8ea1d0ae45 - rb_yield_0
                               at /tmp/ruby-3.1.1/vm_eval.c:1347
  48:     0x7f8ea1d0ae45 - catch_i
                               at /tmp/ruby-3.1.1/vm_eval.c:2297
  49:     0x7f8ea1cfc2b6 - vm_catch_protect
                               at /tmp/ruby-3.1.1/vm_eval.c:2379
  50:     0x7f8ea1cfc44c - rb_catch_obj
                               at /tmp/ruby-3.1.1/vm_eval.c:2405
  51:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  52:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  53:     0x7f8ea1d1266b - vm_call_method
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3750
  54:     0x7f8ea1d02f2d - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  55:     0x7f8ea1d02f2d - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:759
  56:     0x7f8ea1d08fbe - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2211
  57:     0x7f8ea1d0ad23 - invoke_iseq_block_from_c
                               at /tmp/ruby-3.1.1/vm.c:1372
  58:     0x7f8ea1d0ad23 - invoke_block_from_c_bh
                               at /tmp/ruby-3.1.1/vm.c:1390
  59:     0x7f8ea1d0ae45 - vm_yield_with_cref
                               at /tmp/ruby-3.1.1/vm.c:1427
  60:     0x7f8ea1d0ae45 - vm_yield
                               at /tmp/ruby-3.1.1/vm.c:1435
  61:     0x7f8ea1d0ae45 - rb_yield_0
                               at /tmp/ruby-3.1.1/vm_eval.c:1347
  62:     0x7f8ea1d0ae45 - catch_i
                               at /tmp/ruby-3.1.1/vm_eval.c:2297
  63:     0x7f8ea1cfc2b6 - vm_catch_protect
                               at /tmp/ruby-3.1.1/vm_eval.c:2379
  64:     0x7f8ea1cfc44c - rb_catch_obj
                               at /tmp/ruby-3.1.1/vm_eval.c:2405
  65:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  66:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  67:     0x7f8ea1d1266b - vm_call_method
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3750
  68:     0x7f8ea1d02f2d - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  69:     0x7f8ea1d02f2d - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:759
  70:     0x7f8ea1d0960a - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2220
  71:     0x7f8ea1b815ca - load_iseq_eval
                               at /tmp/ruby-3.1.1/load.c:656
  72:     0x7f8ea1b815ca - require_internal
                               at /tmp/ruby-3.1.1/load.c:1132
  73:     0x7f8ea1b8290d - rb_require_string
                               at /tmp/ruby-3.1.1/load.c:1223
  74:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  75:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  76:     0x7f8ea1d130e1 - vm_call_alias
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3189
  77:     0x7f8ea1d02e31 - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  78:     0x7f8ea1d02e31 - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:778
  79:     0x7f8ea1d0960a - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2220
  80:     0x7f8ea1b19684 - rb_ec_exec_node
                               at /tmp/ruby-3.1.1/eval.c:280
  81:     0x7f8ea1b1fbb5 - ruby_run_node
                               at /tmp/ruby-3.1.1/eval.c:321
  82:     0x5638d5abf99b - main
                               at /tmp/ruby-3.1.1/./main.c:47
  83:     0x7f8ea0851c87 - __libc_start_main
  84:     0x5638d5abf9ea - _start
  85:                0x0 - <unknown>
/usr/local/lib/ruby/gems/3.1.0/gems/polars-df-0.2.1-x86_64-linux/lib/polars/data_frame.rb:891:in `write_parquet': cannot convert object to arrow (fatal)
>> df.write_parquet(file.path)
thread '<unnamed>' panicked at 'cannot convert object to arrow', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.26.1/src/datatypes/dtype.rs:230:26
stack backtrace:
   0:     0x7f8e826ee960 - <unknown>
   1:     0x7f8e82715dbe - <unknown>
   2:     0x7f8e826eb805 - <unknown>
   3:     0x7f8e826ee725 - <unknown>
   4:     0x7f8e826eff7f - <unknown>
   5:     0x7f8e826efcba - <unknown>
   6:     0x7f8e826f0678 - <unknown>
   7:     0x7f8e826f03d1 - <unknown>
   8:     0x7f8e826eee0c - <unknown>
   9:     0x7f8e826f0132 - <unknown>
  10:     0x7f8e8035b003 - <unknown>
  11:     0x7f8e816fd673 - <unknown>
  12:     0x7f8e81dea52a - <unknown>
  13:     0x7f8e81707874 - <unknown>
  14:     0x7f8e80853f31 - <unknown>
  15:     0x7f8e806602e8 - <unknown>
  16:     0x7f8e807a8021 - <unknown>
  17:     0x7f8e807e9659 - <unknown>
  18:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  19:     0x7f8ea1d02e31 - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  20:     0x7f8ea1d02e31 - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:778
  21:     0x7f8ea1d08fbe - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2211
  22:     0x7f8ea1d13ac2 - eval_string_with_scope
                               at /tmp/ruby-3.1.1/vm_eval.c:1780
  23:     0x7f8ea1d13ac2 - rb_f_eval
                               at /tmp/ruby-3.1.1/vm_eval.c:1823
  24:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  25:     0x7f8ea1d02e31 - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  26:     0x7f8ea1d02e31 - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:778
  27:     0x7f8ea1d0960a - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2220
  28:     0x7f8ea1d141ce - invoke_block
                               at /tmp/ruby-3.1.1/vm.c:1316
  29:     0x7f8ea1d141ce - invoke_iseq_block_from_c
                               at /tmp/ruby-3.1.1/vm.c:1372
  30:     0x7f8ea1d141ce - invoke_block_from_c_bh
                               at /tmp/ruby-3.1.1/vm.c:1390
  31:     0x7f8ea1d141ce - vm_yield_with_cref
                               at /tmp/ruby-3.1.1/vm.c:1427
  32:     0x7f8ea1d141ce - vm_yield
                               at /tmp/ruby-3.1.1/vm.c:1435
  33:     0x7f8ea1d141ce - rb_yield_0
                               at /tmp/ruby-3.1.1/vm_eval.c:1347
  34:     0x7f8ea1d141ce - loop_i
                               at /tmp/ruby-3.1.1/vm_eval.c:1446
  35:     0x7f8ea1b1d343 - rb_vrescue2
                               at /tmp/ruby-3.1.1/eval.c:903
  36:     0x7f8ea1b1d58a - rb_rescue2
                               at /tmp/ruby-3.1.1/eval.c:884
  37:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  38:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  39:     0x7f8ea1d1266b - vm_call_method
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3750
  40:     0x7f8ea1d02f2d - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  41:     0x7f8ea1d02f2d - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:759
  42:     0x7f8ea1d08fbe - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2211
  43:     0x7f8ea1d0ad23 - invoke_iseq_block_from_c
                               at /tmp/ruby-3.1.1/vm.c:1372
  44:     0x7f8ea1d0ad23 - invoke_block_from_c_bh
                               at /tmp/ruby-3.1.1/vm.c:1390
  45:     0x7f8ea1d0ae45 - vm_yield_with_cref
                               at /tmp/ruby-3.1.1/vm.c:1427
  46:     0x7f8ea1d0ae45 - vm_yield
                               at /tmp/ruby-3.1.1/vm.c:1435
  47:     0x7f8ea1d0ae45 - rb_yield_0
                               at /tmp/ruby-3.1.1/vm_eval.c:1347
  48:     0x7f8ea1d0ae45 - catch_i
                               at /tmp/ruby-3.1.1/vm_eval.c:2297
  49:     0x7f8ea1cfc2b6 - vm_catch_protect
                               at /tmp/ruby-3.1.1/vm_eval.c:2379
  50:     0x7f8ea1cfc44c - rb_catch_obj
                               at /tmp/ruby-3.1.1/vm_eval.c:2405
  51:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  52:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  53:     0x7f8ea1d1266b - vm_call_method
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3750
  54:     0x7f8ea1d02f2d - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  55:     0x7f8ea1d02f2d - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:759
  56:     0x7f8ea1d08fbe - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2211
  57:     0x7f8ea1d0ad23 - invoke_iseq_block_from_c
                               at /tmp/ruby-3.1.1/vm.c:1372
  58:     0x7f8ea1d0ad23 - invoke_block_from_c_bh
                               at /tmp/ruby-3.1.1/vm.c:1390
  59:     0x7f8ea1d0ae45 - vm_yield_with_cref
                               at /tmp/ruby-3.1.1/vm.c:1427
  60:     0x7f8ea1d0ae45 - vm_yield
                               at /tmp/ruby-3.1.1/vm.c:1435
  61:     0x7f8ea1d0ae45 - rb_yield_0
                               at /tmp/ruby-3.1.1/vm_eval.c:1347
  62:     0x7f8ea1d0ae45 - catch_i
                               at /tmp/ruby-3.1.1/vm_eval.c:2297
  63:     0x7f8ea1cfc2b6 - vm_catch_protect
                               at /tmp/ruby-3.1.1/vm_eval.c:2379
  64:     0x7f8ea1cfc44c - rb_catch_obj
                               at /tmp/ruby-3.1.1/vm_eval.c:2405
  65:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  66:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  67:     0x7f8ea1d1266b - vm_call_method
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3750
  68:     0x7f8ea1d02f2d - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  69:     0x7f8ea1d02f2d - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:759
  70:     0x7f8ea1d0960a - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2220
  71:     0x7f8ea1b815ca - load_iseq_eval
                               at /tmp/ruby-3.1.1/load.c:656
  72:     0x7f8ea1b815ca - require_internal
                               at /tmp/ruby-3.1.1/load.c:1132
  73:     0x7f8ea1b8290d - rb_require_string
                               at /tmp/ruby-3.1.1/load.c:1223
  74:     0x7f8ea1cf582b - vm_call_cfunc_with_frame
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3037
  75:     0x7f8ea1d11e69 - vm_call_method_each_type
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3639
  76:     0x7f8ea1d130e1 - vm_call_alias
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:3189
  77:     0x7f8ea1d02e31 - vm_sendish
                               at /tmp/ruby-3.1.1/vm_insnhelper.c:4751
  78:     0x7f8ea1d02e31 - vm_exec_core
                               at /tmp/ruby-3.1.1/insns.def:778
  79:     0x7f8ea1d0960a - rb_vm_exec
                               at /tmp/ruby-3.1.1/vm.c:2220
  80:     0x7f8ea1b19684 - rb_ec_exec_node
                               at /tmp/ruby-3.1.1/eval.c:280
  81:     0x7f8ea1b1fbb5 - ruby_run_node
                               at /tmp/ruby-3.1.1/eval.c:321
  82:     0x5638d5abf99b - main
                               at /tmp/ruby-3.1.1/./main.c:47
  83:     0x7f8ea0851c87 - __libc_start_main
  84:     0x5638d5abf9ea - _start
  85:                0x0 - <unknown>
/usr/local/lib/ruby/gems/3.1.0/gems/polars-df-0.2.1-x86_64-linux/lib/polars/data_frame.rb:891:in `write_parquet': cannot convert object to arrow (fatal)
```

**Comment by ankane** [comment]
New version is out.

**Comment by brandonhilkert** [comment]
Thanks so much!

**Comment by brandonhilkert** [comment]
Using the latest version gives me:

```
>>     df   = Polars::DataFrame.new({ orders: orders })
/usr/local/lib/ruby/gems/3.1.0/gems/polars-df-0.2.3-x86_64-linux/lib/polars/data_frame.rb:4856:in `read_hashes': object type not supported "canceled" (RuntimeError)
```

Here's an abbreviated version of the hash:

```
{"id"=>1,
 "parent_id"=>15116266,
 "status"=>"canceled",
}
```

**Comment by ankane** [comment]
My bad, need to add support for more object types.

**Comment by brandonhilkert** [comment]
No worries! Looking forward to checking it out if/when it's resolved :)

**Comment by ankane** [comment]
Think the common Ruby types should be covered now. Planning for a release within the next week (or you can build from source in the meantime).

**Comment by ankane** [comment]
0.2.4 is out

**Comment by brandonhilkert** [comment]
That did the trick. Thanks so much!

**Comment by ankane** [comment]
Great, thanks for checking!
