### ISSUE TITLE
`error occurred while installing polars-df (0.7.0)` on Ruby 3.3.0

### ISSUE THREAD

**Issue by larouxn** [ankane/polars-ruby#42]
Appears `polars-df` cannot be installed on the just released [Ruby 3.3.0](https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/).

```console
Ruby: 3.3.0
Arch: arm64
OS: macOS 14.2.1
```

Following stacktrace is from `RUST_BACKTRACE=full bundle install` on Ruby 3.3.0.

```console
  --- stderr
INFO: using bindgen with clang args: ["-I/Users/larouxn/.rubies/ruby-3.3.0/include/ruby-3.3.0",
"-I/Users/larouxn/.rubies/ruby-3.3.0/include/ruby-3.3.0/arm64-darwin23", "-fms-extensions", "-fdeclspec", "-O3", "-fno-fast-math", "-ggdb3",
"-Wall", "-Wextra", "-Wextra-tokens", "-Wdeprecated-declarations", "-Wdivision-by-zero", "-Wdiv-by-zero", "-Wimplicit-function-declaration",
"-Wimplicit-int", "-Wpointer-arith", "-Wshorten-64-to-32", "-Wwrite-strings", "-Wold-style-definition", "-Wmissing-noreturn",
"-Wno-cast-function-type", "-Wno-constant-logical-operand", "-Wno-long-long", "-Wno-missing-field-initializers", "-Wno-overlength-strings",
"-Wno-parentheses-equality", "-Wno-self-assign", "-Wno-tautological-compare", "-Wno-unused-parameter", "-Wno-unused-value",
"-Wunused-variable", "-Wmisleading-indentation", "-Wundef", "-D_XOPEN_SOURCE", "-D_DARWIN_C_SOURCE", "-D_DARWIN_UNLIMITED_SELECT",
"-D_REENTRANT"]
  thread 'main' panicked at /Users/larouxn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rb-sys-0.9.83/build/main.rs:64:59:
called `Result::unwrap()` on an `Err` value: "Stable API is needed but could not find a candidate. Try enabling the
`stable-api-compiled-fallback` feature in rb-sys."
  stack backtrace:
     0:        0x102c016a8 - __mh_execute_header
     1:        0x102c209c8 - __mh_execute_header
     2:        0x102bfe3c0 - __mh_execute_header
     3:        0x102c014e8 - __mh_execute_header
     4:        0x102c0311c - __mh_execute_header
     5:        0x102c02e34 - __mh_execute_header
     6:        0x102c03660 - __mh_execute_header
     7:        0x102c03568 - __mh_execute_header
     8:        0x102c01b34 - __mh_execute_header
     9:        0x102c032d4 - __mh_execute_header
    10:        0x102c35aa0 - __mh_execute_header
    11:        0x102c35df8 - __mh_execute_header
    12:        0x1026808d8 - __mh_execute_header
    13:        0x1026831b0 - __mh_execute_header
    14:        0x102680118 - __mh_execute_header
    15:        0x10267fa18 - __mh_execute_header
    16:        0x10267fc00 - __mh_execute_header
    17:        0x102bf9988 - __mh_execute_header
    18:        0x10267fbdc - __mh_execute_header
    19:        0x10268675c - __mh_execute_header
warning: build failed, waiting for other jobs to finish...
make: *** [target/release/libpolars.dylib] Error 101

make failed, exit code 2

Gem files will remain installed in /Users/larouxn/.gem/ruby/ruby-3.3.0/gems/polars-df-0.7.0 for inspection.
Results logged to /Users/larouxn/.gem/ruby/ruby-3.3.0/extensions/arm64-darwin-23/3.3.0-static/polars-df-0.7.0/gem_make.out

  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/source/rubygems.rb:205:in `install'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:132:in `do_install'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/worker.rb:62:in `apply_func'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/worker.rb:54:in `process_queue'
  /Users/larouxn/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing polars-df (0.7.0), and Bundler cannot continue.

In Gemfile:
  polars-df
```

**Comment by ankane** [comment]
Hi @larouxn, this is fixed in 93610cce8421d52ae9b5ce89dd11cfb2386b9708 (and will cut a new precompiled version at some point).
