### ISSUE TITLE
M1 Mac Arch issue

### ISSUE THREAD

**Issue by DaddyWozBucks** [ankane/polars-ruby#9]
I am trying to upgrade my Rover (awesome gem) to use Polars and while the gem installation completes and my `Gemfile.lock` has entries for both x86 and arm64 
```
    polars-df (0.3.1)
      rb_sys
    polars-df (0.3.1-arm64-darwin)
    polars-df (0.3.1-x86_64-linux)
```
when ever I try and run the code I get the error:

`mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'`

Any idea how to fix this? Macbook Pro M1 Pro chip

**Comment by ankane** [comment]
Can you paste the full stack trace? Also, does updating Bundler to the latest version fix it?

**Comment by DaddyWozBucks** [comment]
Here is the stack trace from trying to run a spec
```
                                                                                                                                                 
An error occurred while loading ./engines/excel_data_services/spec/services/excel_data_services/v4/upload_pricings_spec.rb.
Failure/Error: require File.expand_path("../config/environment", __dir__)

LoadError:
  dlopen(/Users/warwick-itsmycargo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.3.1/lib/polars/polars.bundle, 0x0009): tried: '/Users/warwick-itsmycargo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.3.1/lib/polars/polars.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/warwick-itsmycargo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.3.1/lib/polars/polars.bundle' (no such file), '/Users/warwick-itsmycargo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.3.1/lib/polars/polars.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) - /Users/warwick-itsmycargo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.3.1/lib/polars/polars.bundle
# ./engines/excel_data_services/lib/excel_data_services/engine.rb:11:in `<top (required)>'
# ./engines/excel_data_services/lib/excel_data_services.rb:3:in `<top (required)>'
# ./config/application.rb:20:in `<top (required)>'
# ./config/environment.rb:4:in `require_relative'
# ./config/environment.rb:4:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `<top (required)>'
# ./engines/excel_data_services/spec/services/excel_data_services/v4/upload_pricings_spec.rb:3:in `require'
# ./engines/excel_data_services/spec/services/excel_data_services/v4/upload_pricings_spec.rb:3:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- /Users/warwick-itsmycargo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/polars-df-0.3.1/lib/polars/3.2/polars
#   ./engines/excel_data_services/lib/excel_data_services/engine.rb:11:in `<top (required)>'
```

Running bundler 2.4.5, upgrading to 2.4.7 doesnt seem to do anything

**Comment by ankane** [comment]
For some reason, it looks like it's using the source version instead of the `arm64-darwin` one. Can you paste the output of `bundle platform`?

Also, not sure why the source version would have compiled for a different architecture. Was it compiled on a different machine?

**Comment by DaddyWozBucks** [comment]
```
Your platform is: arm64-darwin-22

Your app has gems that work on these platforms:
* arm64-darwin-22
* ruby
* x86_64-linux

Your Gemfile specifies a Ruby version requirement:
* ruby 3.2.0

Your current platform satisfies the Ruby version requirement.
```

Everything compiled on this machine. Our app runs in x86 (docker image in k8s) but our dev machines are mostly M series macs so maybe thats contributing?

**Comment by ankane** [comment]
Unfortunately, I'm not able to reproduce on `arm64-darwin-22`, so think it's something specific to your setup.

```sh
bundle init
bundle lock --add-platform ruby
bundle lock --add-platform x86_64-linux
bundle add polars-df
bundle exec ruby -e "require 'polars-df'"   
```

If you're able to create a minimal repro script, happy to look into it more.
